### PR TITLE
feat: check 1, 2, 3, 4

### PR DESCRIPTION
**Pull request by aryannarora**
Now, this would open a new issue.

### CODE REVIEW

**Comment by gr2m** [comment]
no issue 😢🐼

**Comment by aryannarora** [comment]
Uh oh. @gr2m I think the Glitch server slept after some inactivity. :p 
I have created a GIF for you but you can also try yourself cause that is more fun. 😄 

dockup

**Comment by aryannarora** [comment]
I'm thinking to change the label to `dockup`. That would be more meaningful, right?

**Comment by gr2m** [comment]
label is easy to change, I have no preference myself :) 

What you can do is to setup https://uptimerobot.com/ to monitor your app hosted on glitch. It will ping it once per minute so it won’t fall asleep :)

**Comment by aryannarora** [comment]
That's cool.  I'm gonna get it up. 😀

**Pull request merged**
